---
- name: Log some_parameter defined from role1 tasks file
  debug:
    msg: "***** Log 0003: some_parameter={{ some_parameter }}"
  when: some_parameter is defined
- name: Log some_parameter undefined from role1 tasks file
  debug:
    msg: "***** Log 0003: some_parameter is undefined"
  when: some_parameter is undefined
